name: printer_agent
description: Cross-platform POS print agent for Windows and Android.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # ── Socket ──────────────────────────────────
  socket_io_client: ^2.0.3+1

  # ── ESC/POS formatter (all printer types) ───
  esc_pos_utils_plus: ^2.0.3
  usb_serial: ^0.5.0

  # ── Printer drivers (LAN + USB + Android BT)─
  # flutter_pos_printer_platform_image_3: ^1.2.1
  flutter_thermal_printer: ^1.2.1+1
  thermal_printer_plus: ^1.0.0

  # ── Windows Bluetooth only ──────────────────
  flutter_thermal_printer_windows: ^0.0.1

  flutter_blue_plus: ^1.31.15

  # ── Android background service (socket lives here)
  flutter_background_service: ^5.0.10
  flutter_local_notifications: ^17.2.2

  # ── Android runtime permissions ─────────────
  permission_handler: ^11.3.1
  device_info_plus: ^10.1.0

  # ── Windows system tray ─────────────────────
  system_tray: ^2.0.3

  # ── Save printer configs ─────────────────────
  shared_preferences: ^2.3.2

  # ── PDF ─────────────────────
  pdf: ^3.11.3
  printing: ^5.14.2

  # ── Unique job IDs ───────────────────────────
  uuid: ^3.0.7
  http: ^1.2.0
  win32: ^5.5.3
  ffi: ^2.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Black.ttf
          weight: 900
        - asset: assets/fonts/Montserrat-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Montserrat-Thin.ttf
          weight: 100
    - family: Rupee_Foradian
      fonts:
        - asset: assets/fonts/Rupee_Foradian.ttf
          weight: 400
